# logging 설정
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug
  # discord log back
  discord:
    webhook-url: https://discord.com/api/webhooks/1198101297774215251/vkB0nSaz-h2Mh8M_trt96jBRQOkmPc3hmjInyL9MConbp6jWdcVisGRF3-lKgV9zHyNP
    config: classpath:logback.xml

# console 색상
spring:
  output:
    ansi:
      enabled: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


# 오류 처리
server:
  error:
    include-exception: true
    include-stacktrace: always

  #port 설정
  port: 8080